#!/usr/bin/env bash
set -euo pipefail

DATE="2026-03-16"
REPORT_DIR="/tmp/stock-reports/reports"
REPORT_PATH="$REPORT_DIR/${DATE}-afternoon-report.md"
TMP1="$REPORT_DIR/.${DATE}-afternoon-report.md.tmp"
TMP2="$REPORT_DIR/.${DATE}-afternoon-report.md.tmp.retry"

# Read metal prices
read XAU XAG RATIO < <(awk -F= '/XAU/{x=$2}/XAG/{y=$2}/RATIO/{r=$2}END{print x,y,r}' /tmp/stock-reports/.metals.txt)

# Render function
render() {
  local out="$1"
  cat > "$out" << REPORT_EOF
# Afternoon Deep Stock Research Report - March 16, 2026

**Report Date:** March 16, 2026 (Monday)  
**Session:** Afternoon Deep Research  
**Generated by:** OpenClaw Stock Research Agent

---

## Executive Summary

This afternoon deep research report provides comprehensive technical analysis of major U.S. indices, sector performance, individual stock deep dives, and precious metals analysis.

---

## 1. Market Overview - Major Indices

### 1.1 S&P 500 (SPY)
![SPY Daily Chart](../charts/${DATE}/SPY.png)

### 1.2 NASDAQ-100 (QQQ)
![QQQ Daily Chart](../charts/${DATE}/QQQ.png)

### 1.3 Dow Jones Industrial Average (DIA)
![DIA Daily Chart](../charts/${DATE}/DIA.png)

---

## 2. Gold/Silver Ratio Analysis

- Gold (GC=F): **$XAU**
- Silver (SI=F): **$XAG**
- **Gold/Silver Ratio: $RATIO**

---

## 3. Individual Stock Deep Dives

### 3.1 NVIDIA Corporation (NVDA)
![NVDA Daily Chart](../charts/${DATE}/NVDA.png)

### 3.2 Apple Inc. (AAPL)
![AAPL Daily Chart](../charts/${DATE}/AAPL.png)

### 3.3 Tesla Inc. (TSLA)
![TSLA Daily Chart](../charts/${DATE}/TSLA.png)

---

*Disclaimer: This report is for informational purposes only.*
REPORT_EOF
}

atomic_write_once(){
  local tmp="\$1"
  render "\$tmp"
  [[ -s "\$tmp" ]] || return 1
  grep -q '^# ' "\$tmp" || return 1
  mv "\$tmp" "$REPORT_PATH"
}

if ! atomic_write_once "$TMP1"; then
  rm -f "$TMP1"
  if ! atomic_write_once "$TMP2"; then
    rm -f "$TMP2"
    echo "ATOMIC_WRITE_FAILED" >&2
    exit 11
  fi
fi

echo "REPORT_GENERATED_SUCCESSFULLY"
